import Head from "next/head";
import Product from "@/container/product";
import { Layout } from "antd";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ex3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Product />
      </Layout>
    </>
  );
}
